### ISSUE TITLE
Weird (un-themed?) green tint on some toggles/buttons

### ISSUE THREAD

**Issue by wzxu** [napalmpapalam/napalm-theme-zed#2]
Hello. Thanks for the nice theme. 

I'm seeing these out-of-place green tint on some toggles/buttons, which I don't suppose is intended? On latest Preview.
<img width="841" alt="18566" src="https://github.com/napalmpapalam/napalm-theme-zed/assets/5619348/b3b29943-67ef-43f0-af16-3d1d85d5abd6">
<img width="743" alt="58145" src="https://github.com/napalmpapalam/napalm-theme-zed/assets/5619348/6c3ebb7a-74ae-450d-b980-5b0628d67caa">

**Comment by napalmpapalam** [comment]
Hey, thanks. It's fixed in [napalm-theme-zed#3](https://github.com/napalmpapalam/napalm-theme-zed/pull/3).

This pull request should close this issue: [extensions#86](https://github.com/zed-industries/extensions/pull/86)

**Comment by wzxu** [comment]
Thanks 👍
